# /////////////////////////////////////////////////////////
# ┏━┳┳━┳━┳━┳┓┏┳━┳━┳━━┳━┳━┳━┳┳┳┳━┳┓
# ┃┃┃┃┃┃┏┫┃┃┗┛┃━┃╻┣┓┏┫━┫┃┃╻┃┃┃┃┃┃┃
# ┃┃┃┃┃┃┗┫┃┃┃┃┃━┃╻┃┃┃┣━┃┏┫╻┃┃┃┃┃┃┃
# ┗┻━┻━┻━┻━┻┻┻┻━┻┻┛┗┛┗━┻┛┗┻┻━━┻┻━┛
# /////////////////////////////////////////////////////////
# This Plugin is for Private Use On Frost Network Only!
# Plugin Developed By EmeraldMC!
# Discord is Havana#3558
# For Commissions Please Dm My Discord
# /////////////////////////////////////////////////////////
# █▀▀─█▀▄─▄▀▀▄─▄▀▀─▀█▀─█─█─▄▀▀▄─█▀▀
# █▀▀─██▀─█──█──▀▄──█──█▀█─█──▄─█▀▀ - frosthcf.tk | 19185
# ▀───▀─▀──▀▀──▀▀───▀──▀─▀──▀▀──▀──
# /////////////////////////////////////////////////////////
#
# /////////////////////////////////////////////////////////
# In combat Message "keep-out-message"
# default cooldown "0" max cooldown is 60 seconds
# /////////////////////////////////////////////////////////
keep-out-message: "You Cant Enter Spawn In Combat"
combat-cooldown: 0
